### ISSUE TITLE
Processed Fever train and eval data

### ISSUE THREAD

**Issue by weihangzhang** [minwhoo/CrossAug#1]
Hi,

Thanks very much for open-sourcing your code and data.
I found that the provided link of the processed Fever train and eval data is no longer valid. Could you please kindly provide an updated link? I would really appreciate the help.

Best,
Weihang

**Comment by minwhoo** [comment]
@weihangzhang Hey I'm not sure if you've gotten access to the link, but I've replaced the train data download link with a direct upload to the github repo instead, in the `data/` subdirectory. Hope that fixes the issue.

**Comment by weihangzhang** [comment]
Hey @minwhoo , thanks very much for providing the link. I actually meant to post this on another repo, really sorry about the confusion.
